resourcePackages:
  - hu.home.springbootcrud
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: "1.0.0"
    title: Spring Boot CRUD Services
    description: |
      Spring Boot Creat Read Update Delete Services